### ISSUE TITLE
Memory error on CRAN with test of memory access errors using AddressSanitizer

### ISSUE THREAD

**Issue by dlm** [compTAG/r-tda#17]
Memory test is failing on CRAN when performing some memory checks.  See https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-ASAN/TDA/00check.log for error log.

**Comment by dlm** [comment]
Looks like you fixed the memory error.  Did you push a new release to CRAN?

**Comment by jisuk1** [comment]
It was not the memory error from https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-ASAN/TDA/00check.log but for the latest version of TDA to 1.6.2 (which was also related to another memory error).

But I think I roughly figured out the issue. Seems like upcasting from Gudhi::Alpha_complex to Gudhi::Simplex_tree when at the function return from AlphaComplexFiltrationGudhi() function in tdautils/gudhiUtils.h to alphaComplexDiag() function in alphaComplex.h. Then stack-use-after-scope error happens when num_simplices() is called from the upcasted returned object.

I didn't investigate in full detail, but seems like upcasting inside the function AlphaComplexFiltrationGudhi() resolves the stack-use-after-scope error. So after checking few more things, I am planning to push this to CRAN.

**Comment by jisuk1** [comment]
So I think I figured it out.
The memory issue due to something like a shallow move of 'Simplex_tree' class.
In 'Simplex_tree' class, 'root_' is of type 'Simplex_tree::Siblings = Simplex_tree_siblings' and 'filtration_vect_' is of type 'std::vector<Simplex_handle>'. Both type contains 'Simplex_tree_siblings *', and a 'Simplex_tree' class variable contains the pointer to its 'root_'. Hence, when the move constructor is called, then the address of 'old.root_' is still preserved in new 'Simplex_tree', although 'old' is deleted.
Temporarily disable move constructor so that copy constructor is used instead.

**Comment by dlm** [comment]
Great!  I was looking through the commit history.  I see that you made a branch fix-memory.  Let me know if you want any help merging it into master or tagging the version that you released.

**Comment by jisuk1** [comment]
Yes, I merged it into master and deleted fix-memory branch.
